### ISSUE TITLE
Caching of user input appears to not be working

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1334]
To replicate:

- Go to https://ulib.iupui.edu/services/ILLTest 
- Input : 'very long title that we can't possibly find because I made it up'
- You’ll see the result appears with no title
- Correct it
- Try again, and it will not be there

**Comment by markmacgillivray** [comment]
This is working on dev and on live only appears to not be working because of the previous missing titles not being picked up to show the user the extra metadata boxes. I have also adjusted further for some bad year values we have been receiving from the new find metadata algorithm. Fixed now, will push to live soon.

**Comment by JosephMcArthur** [comment]
Still having some issues here. For example:

Go to: https://ulib.iupui.edu/services/ILLTest
Put in: Exposing errors related to weak memory in GPU applications
See that you get tittle & 2016. 
Go to fill in journal (Proceedings of the 37th ACM SIGPLAN Conference on Programming Language Design and Implementation - PLDI 2016)
It appears to not save the value.

**Comment by markmacgillivray** [comment]
The IUPUI ILLTest page still points to our live API. So I have tested this on our own instantill/setup dev page.

There were a number of complexities causing this, so it has taken quite a while to resolve (about a day).

* our crossref reverse lookup was having trouble extracting the journal title in some cases, that has been improved.

* the journal title above is not actually the journal title for the article at the given DOI - the article has been published more than once and has more than one valid record in crossref. They have different journal titles.

* Now that we do pick up journal titles more accurately from reverse lookups, we do get a journal title for this, but it is a different one from the one given above.

* So I have also changed it so that a user can override a journal title even if we did already get one and serve it to them, so in the case of the above one you can actually click to say it is not the right thing if you think it is wrong, and provide a new journal title

* the journal title provided by a user will then be saved and used as the journal title for the article in our catalogue, and future lookups for the same article title / DOI will provide responses that show that journal title provided by the previous user

* note that it would still be possible for someone else to put in a different DOI for this same article, and get back a different record

* also, technically, we are now allowing users to provide us with wrong metadata - in the example in this issue, we are now saving the journal title that applies to the SECOND publication of this article but we are saving it alongside the DOI of the FIRST publication

* however, it now works as desired, so closing the issue

(NOTE it still will not work on the IUPUI test site until I next update our live API)

**Comment by JosephMcArthur** [comment]
Thanks for this Mark! Some of the errors you catch along the way here feel like things I've noticed going wrong elsewhere so I think this was pretty valuable to do!
