### ISSUE TITLE
Refactor demo & setup code

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1513]
To be discussed.

> the setup/demo pages for instantill and shareyourpaper are terrible (code-wise; they look nice). It was never clear how the demos were supposed to interact from the designs, and no thought was put into how we should do that, or where certain parts would need to run and where not, and how they should best interact with the UI. These pages need to be refactored from scratch, to keep the same design and workflow, but entirely operationally different underneath (and can include things we now know we want like kicking off a check earlier in the page load, and possibly before config is retrieved). 3 days.

#1510

**Comment by JosephMcArthur** [comment]
Immediate thoughts. I think we can make demo code simpler by not having it all be dynamic. 

Seemingly related to: #1499 and #1470.

**Comment by JosephMcArthur** [comment]
A few notes from our doc / discussions that I recall:

## Setup

* refactor all of backend
* don't show 'old' config option
* have frontend be indistinguishable, except:
  * a 'alert bar' style element which shows up when there are changes on the set up page that aren't reflected in the site code.  
  * handle login on the setup pages themselves (copying over relavant content from /account). 
* leave major copy changes to joe
* have embeds aware of when they're on setup pages, and able to respond different to normal

## Demo

* can be on stand-alone pages now, so that it's more similar to set up
* responses can be hardcoded, rather than live
* generally aim to clean the code to make it understandable / maintainable
* otherwise, indistinguishable from now.

**Comment by JosephMcArthur** [comment]
- [ ] when we've done the setup, consider changing config names

**Comment by JosephMcArthur** [comment]
# ILL Setup
# ILL Demo# SYP Setup

**Comment by JosephMcArthur** [comment]
## ILL Setup

- [ ] make tickboxes for setting css: false and bootstrap: false to `embed-advanced`. I've made some pre-made tick boxes there with IDs, but it would be great to have you double check those all hook up. 
- [ ] url's don't update when moving from section to section. Is that expected? I still don't love the ?doi= turning up on these pages
- [ ] can you make the buttons for login do what they say they should do
- [ ] On `Interlibrary loans: Submission (1/2)` we should be able to get to 2/2, but it doesn't seem like we can now.
- [ ] can you move what's left of the embed screen that was on the LHS onto the RHS?
- [ ] When you click `Go to Menu`, the button that normally reads `Get Started` reads save and continue. I think it should probably just continue to read `Get Started`
- [ ] Copy and pasting the code to a new page doesn't actually work. I don't see IDs in the embed code now. see: https://josephmcarthur.github.io/playground/new-syp.html

## ILL Demo

- [ ] Where is the page for this? I was expected it at /ill2/demo

## SYP Setup

- [ ] propagate (almost) all of the changes in InstantILL here

## SYP Demo

- [ ] when you do the first deposit, the RHS doesn't change to allow you to move on in the demo.

I can't do any more testing after that.

**Comment by markmacgillivray** [comment]
Some Qs to clarify (going to bed now, will fix when I get up):

I thought you wanted the ?doi turning up - which pages do you want it to turn up and which pages not?

what do you mean about buttons for login? what do they say, and what should they do? which buttons are you meaning?

what do you mean by the "what's left of the embed screen on the LHS?"

I didn't know there was a specific ILL demo page to do - the old instantill folder doesn't have one called demo in it. Where would the demo be?

what changes do you mean should be propagated from instantill to syp? 

SYP demo - balls, that was working, I made a change for tabbing through things on the setup pages though that must have broke that, will fix.

**Comment by JosephMcArthur** [comment]
I think some of this will be clearer when you look. But, some won't, and answer for the are below:

> I thought you wanted the ?doi turning up - which pages do you want it to turn up and which pages not?

Yes, I wanted it on all pages except demo & setup

> what do you mean about buttons for login? what do they say, and what should they do? which buttons are you meaning?

There is one button that says login, and it should do the same thing as pressing enter in the email box does now

> I didn't know there was a specific ILL demo page to do - the old instantill folder doesn't have one called demo in it. Where would the demo be?

So, at some point I totally deleted the demo code. The commit for that is here:

https://github.com/OAButton/website/commit/e1232fdcd50c4f598a707f5ef53a21e51c55debe#diff-120b9b1c3cc4e02a90087a0ee683fb17

The demo code there should be a good starting point to move to a separate page like the SYP code. 

> what changes do you mean should be propagated from instantill to syp?

Whatever you do for InstantILL also needs to be done for syp

**Comment by markmacgillivray** [comment]
I can't find an ILL: submission 2/2. It doesn't appear to be there in the old instantill setup page either. Can you look and let me know which section content it is that you expect to show up there, perhaps it needs renamed as well

**Comment by JosephMcArthur** [comment]
okay I've committed a fix for this!

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
- [ ] ill2 demo to standalone (like syp demo)
- [ ] fix page width issues
- [ ] extra comma when not logged in for embed script
- [ ] logged in embed script also doesn't work still: https://josephmcarthur.github.io/playground/new-syp.html

**Comment by JosephMcArthur** [comment]
I have set up two test pages for the new embeds:

* https://josephmcarthur.github.io/playground/new-syp.html
* https://josephmcarthur.github.io/playground/new-instantill.html

- [ ] on neither page does ?doi=something get added when I search a DOI as it should. I've asked this to be turned off only on demo / setup pages
- [ ] on https://josephmcarthur.github.io/playground/new-syp.html?doi=10.1186/1758-2946-3-47 the heading doesn't show correctly. e.g see the heading here: https://josephmcarthur.github.io/playground/syp-dev?doi=10.1186/1758-2946-3-47
- [ ] attempting to deposit from here: https://josephmcarthur.github.io/playground/new-syp.html?doi=10.1126/scitranslmed.3001922 seems to not work. Just says it's depositing endlessly
- [ ] Using https://josephmcarthur.github.io/playground/new-syp.html?doi=10.1126/scitranslmed.3001922&email=joe@arl.org (note the email passed in the URL) hides the email input box. Is it still passing it in the background? If so, great, very nice to hide the email box when it's not needed. 
- [ ] when using https://josephmcarthur.github.io/playground/new-syp.html?doi=10.15650/hebruniocollannu.89.2018.0221 or maybe any link like this the doi is not put in the search box when searching. 
- [ ] for both our test dois, 10.1086/704224 & 10.1126/scitranslmed.3001922 it's saying they can't shared. This doesn't seem to be a problem with permissions https://permissions.shareyourpaper.org/doi/10.1126/scitranslmed.3001922 & https://permissions.shareyourpaper.org/doi/10.1086/704224

**Comment by markmacgillivray** [comment]
Changed the settings for showing the ?doi= or not, just hadn't put that new setting in yet. For text size in buttons, I have adjusted the default size so it looks a little bigger on your test pages.

**Comment by markmacgillivray** [comment]
I didn't use difftest for these changes, because I didn't know which things would be right and which would be wrong. I could only test what I thought something should do, trying to guess from the old code we had (the point of the refactor being that it wasn't easy to understand that). There are definitely differences in what it does now, because some layouts and texts have been slightly changed to fit a better logic on the code, so getting loads of tiny errors wasn't any use to actually making the code better. That's why you're finding some slight changes where I wasn't sure what to do, and once we complete these, it should be done.

**Comment by markmacgillivray** [comment]
10.1086/704224 result has been fixed, there were two lines commented out from my last set of testing that meant the stuff about not sharing the PDF was still showing up, but apart from that seemed right. So now it looks the same as the live SYP.

For the other DOI 10.1126/scitranslmed.3001922 there is something else going on with that one, will need to investigate tomorrow.

**Comment by markmacgillivray** [comment]
What do you mean about how preview / save & continue works now? If I look at syp2/setup I do still see preview buttons there. Where are you not seeing them that you want to see them? They should still work the same way, e.g. a preview button tries to run a preview with whatever is the value set by the user for previewing things, or by a default value. The save button does not trigger a preview but advances the RHS to the next section, same as before. Of course in reality "preview" and "save" are inaccurate terms for how the embed actually saves config now, but you wanted the page to stay as similar as possible, so that is how it looks, even though the functionality does not match.

As far as I can tell, the default value for syp setup was that DOI which is not actually a real DOI, and SYP does still show a "this is not a valid DOI". I can turn that off as well, in addition to where we have turned it off for instantill, but of course for SYP the system would not be able to do anything else without a valid DOI. Or, you can let me know which DOI you want the setup page to use as a default one.

Note that the demo DOIs work from the demo page, not the setup page, as setup can be used by the real user, not just from the demo account.

**Comment by markmacgillivray** [comment]
SYP fixed to not allow title searches through, that became possible due to merging ILL and SYP code. Also altered the "double check your DOI" error text back to match what it was on live.

**Comment by markmacgillivray** [comment]
For the styling issue on ill2/demo is that for you to do? Or are you wanting me to do something there? I didn't change any of that, it was just copied straight across from the old pages, so not sure what I can do about it.

**Comment by markmacgillivray** [comment]
For the ones where you are having trouble getting it to actually submit anything, can you try altering your code on your test pages? At the moment you have not set the API address when you call the embed, so they are trying to send to the live API and failing because it does not currently exactly match what is on dev.

You need to add api: https://dev.api.cottagelabs.com/service/oab into your call to the embed, next to where you would put your uid (not in the actual config part).

The code you copy from the setup pages does not tell you that because no user will actually do that from dev.

**Comment by JosephMcArthur** [comment]
> You need to add api: https://dev.api.cottagelabs.com/service/oab into your call to the embed, next to where you would put your uid (not in the actual config part).

Attempted to do that!

I'm now seeing different errors for things like: https://josephmcarthur.github.io/playground/new-syp.html?doi=10.15650/hebruniocollannu.89.2018.0221 which now gives me the AAM upload page incorrectly. https://josephmcarthur.github.io/playground/new-syp.html?doi=10.1186/1758-2946-3-47, which should allow me to do a redeposit, also tells me it's missing a file when I try and upload.

> The code you copy from the setup pages does not tell you that because no user will actually do that from dev.

Occasionally users do, including important ones like us ;) and our partners. So, if you could add that it would be great.

> For the styling issue on ill2/demo is that for you to do? Or are you wanting me to do something there? I didn't change any of that, it was just copied straight across from the old pages, so not sure what I can do about it.

Yup, I'll do it. 

> I didn't use difftest for these changes, because I didn't know which things would be right and which would be wrong. I could only test what I thought something should do, trying to guess from the old code we had (the point of the refactor being that it wasn't easy to understand that). There are definitely differences in what it does now, because some layouts and texts have been slightly changed to fit a better logic on the code, so getting loads of tiny errors wasn't any use to actually making the code better. That's why you're finding some slight changes where I wasn't sure what to do, and once we complete these, it should be done.

FYI, whatever the response is on live atm with these dois (and, the ones at https://shareyourpaper.org/test) can be used to eyeball if things look please. I'd have thought all the above bugs were fairly obvious, so it would be great if you could do a quick check before sending my way.

**Comment by markmacgillivray** [comment]
For the ILL demo part3, the only thing I can see there is that the embed shows  a result with "complete request" button, and the RHS text says "hit the complete request button", and when you do that it shows the fake ILL data table. It seems to fit with what is described, and I don't know how the old one used to look, so can you detail a bit more what it should do? 

Just now, after part3, it shows fakeill, and the RHS info appears to make sense in that context too. And the button to continue after seeing the fake ILL table (in part5) makes sense as well, in the context. So what should it show instead, in those stages? Then it goes on to part6, which is just the conclusion page, so presumably that part is OK.

**Comment by markmacgillivray** [comment]
For the submit request over email at this link: https://josephmcarthur.github.io/playground/new-instantill.html?doi=10.1186/1758-2946-3-47

I tried it and it appears to work. It results in a completion page where I see my confirmation code. What part of it should be different? Or was this just from the embed trying to hit the wrong API?

**Comment by markmacgillivray** [comment]
dev API address added to code to copy on dev. Your different errors listed in relation to that are working fine now too. I'd already checked a few of these against the live one to see if they ended up where expected, but there were ones where it was ambiguous in the code, which is the point of the refactor. Although the page differences may look visually large, it has only been a few settings tweaks to make the changes necessary for the above. I had TODO tags on the code for two particular workflow items needing resolved, and your testing and descriptions above has enabled that. But I have another workflow to ask about as well:

If the article is not already available, and archiving is allowed, if permission is not required then they see the file uploader. But permission is required, they should see the buttons to send a permission request email, right? If it can't be shared even with permission, then the remaining option appears to be that they can make a dark deposit (showing them the file uploader again), BUT it is also possible that the embed config can have dark deposit turned off. In that case, what should the user see? Currently I have it showing the email permission request button in that scenario too, and that appears to be what it did in the old code, but is that what you want? The old code did not refer to the permission_required option at all, it only showed the permission request thing where dark deposit had been turned off in config. This is probably due to the permissions API changing over the time that we had written that embed. Again, it is a simple change to the code to get it to show something else for the case where dark deposit is turned off, although I'd also need to know what you want it to say in that case, as it doesn't look like a result for that existed in the old code.

**Comment by markmacgillivray** [comment]
Just a note to review where I am at now - the only issue from above that I am still working on is where the DOI 10.1126/scitranslmed.3001922 seems to be giving us wrong results, that is still under investigation. Everything else has commentary for you above.

**Comment by markmacgillivray** [comment]
The issue with 10.1126/scitranslmed.3001922 has been fixed as well now, appears to give same answer on new embed as it does on live. It appears to have been just a problem with dirty data from earlier testing getting stuck in dev for that record.

**Comment by JosephMcArthur** [comment]
Start of my testing today:

- [ ] when clicking: https://josephmcarthur.github.io/playground/new-syp.html?doi=10.1086/704224&confirmed=BgP4bkjDhLembVSbnogNJA%3D%3D&email=joe@arl.org the page appears to wipe confirmed and email.

**Comment by JosephMcArthur** [comment]
I've made lots of updates to the comment above, so don't rely on emails (basically never do... but wanted to be 100% sure)

**Comment by markmacgillivray** [comment]
Regarding some "do another" being bold - I have removed that, and removed any other use of bold. As far as I can tell, this means they are consistent - but any bold ones there were only bold because that is how they were on the old embed. Some buttons use the actual button class but others don't, they're just text. So, if you mean consistent should all be buttons, then they're not that, because they weren't that before.

**Comment by markmacgillivray** [comment]
each RHS section is in a div with an ID attribute and a class "section". You can add an attribute to that div called "preview" and the value provided there will be used when the preview button is hit. And/or you can add an attribute called "save" and the value of that will be used when the ave button is hit.

**Comment by markmacgillivray** [comment]
I can't replicate the error you describe when using 10.fake. If I follow that link, I get the first error which is expected, then I change the DOI in the search box and it searches and continues as normal, and updates the page URL as well. Can you check again?

**Comment by JosephMcArthur** [comment]
> Regarding some "do another" being bold - I have removed that, and removed any other use of bold. As far as I can tell, this means they are consistent - but any bold ones there were only bold because that is how they were on the old embed. Some buttons use the actual button class but others don't, they're just text. So, if you mean consistent should all be buttons, then they're not that, because they weren't that before.

Can we make them consistent then please? I think it probably makes sense for them to all use the proper button class. 

Are there other inconsistent uses of code for the styling (or anything else) you've spotted?

**Comment by JosephMcArthur** [comment]
Before we shut this:

- [ ] Turn as much of the above into a difftest as possible.

I can do that, I just want to make a note.

**Comment by JosephMcArthur** [comment]
> I can't replicate the error you describe when using 10.fake. If I follow that link, I get the first error which is expected, then I change the DOI in the search box and it searches and continues as normal, and updates the page URL as well. Can you check again?

I can still replicate it, but I realized my instructions may have mislead you as I accidentally copied a search URL.

* go to https://josephmcarthur.github.io/playground/new-syp.html
* put in 10.fake
* not the error, all good
* put in: 10.1186/1758-2946-3-47
* you'll see it ask you to input all required fields.

**Comment by JosephMcArthur** [comment]
# Comment for my testing today

Expect updates to it, don't trust email :) 

- [ ] on https://josephmcarthur.github.io/playground/new-syp.html?doi=10.15650/hebruniocollannu.89.2018.0221 the email box is coming up incorrectly

**Comment by markmacgillivray** [comment]
10.fake problem solved, sorry I had missed that. Also pressing back takes you back to embed start search page now.

**Comment by markmacgillivray** [comment]
Styling inconsistencies seemed to be around buttons (everything else is just text and headers that look fine, and some input boxes). I have now changed all buttons to have the _oab_button class (or the bootstrap ones if the settings dictate that) - except for any links which are inline with text in a paragraph, in which case they are still just text because a button would look weird in the middle of a paragraph. However, any uses of bolding or italics have been removed. Also, a previous fix removed the underlining from our default css.

**Comment by markmacgillivray** [comment]
About the 2011 science translational medicine bit being a slightly different colour, the tags that surround it are bold tags with a specific color code added to them. It is like that because that is what was in the old embed.

**Comment by JosephMcArthur** [comment]
and that color is set by us, right, it's not dependent on user styling?

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Yeah it is set by us, directly in the surrounding tag.

Also, other links that were not buttons that I changed to buttons are now back to not being buttons again. All such non-button links now have no styling tags applied to them, so they are just inline text links.

**Comment by JosephMcArthur** [comment]
> Yeah it is set by us, directly in the surrounding tag.

Let's remove that then. Instead, let's try making it Italic. I can understand why we made it different, however, we shouldn't use color for it.

**Comment by JosephMcArthur** [comment]
> Also, other links that were not buttons that I changed to buttons are now back to not being buttons again. All such non-button links now have no styling tags applied to them, so they are just inline text links.

So, to me they still look underlined, which I presume is a browser default. I can't find any hard and fast rule for how they should be styled (e.g internal link vs internal link or above the button vs below the button) that feel perfect. However, I'd say let's bold & underline them all.

**Comment by markmacgillivray** [comment]
Yes, by default a link is underlined by a browser, so with all other styling removed, that is what you see. I'll add bold to them all as well.

**Comment by markmacgillivray** [comment]
Do you want ALL non-button links bolded, or only those ones that are separate from surrounding text? e.g. should ones that appear inline in a sentence also be bolded?

**Comment by markmacgillivray** [comment]
The montana page has an extra 5px padding left between work and under because their css specifically defines an additional 5px padding for a span that comes after another span. There is nothing we can do about that unfortunately, and it is not in default bootstrap as far as I can tell, so is just going to be an odd feature of their page because they appear to want spans to have that spacing.

**Comment by markmacgillivray** [comment]
Why do you want the "Do another" link only to be a button on the congrats page? Why not the other pages that use it? The three other endings for SYP all have that button in the ending, on a separate line, and as I've defined it at the moment it would be a bit odd to alter the styling of it for just that one case, but I can do if you want. Just clarifying, in case you are not aware it comes out as a string on those places too.

**Comment by markmacgillivray** [comment]
autorunparams would have been set on your account during testing, when I was working on the code. You can remove them by going to the setup page and using the config param to get rid of them, that is ?config.autorunparams=false. Then they will disappear from your config. They will only show up in user configs if the user does set some alternate values for them.

**Comment by markmacgillivray** [comment]
To get a list of all the config value names, the most up to date way is to always check the setup pages themselves. Given that we have changed quite a lot again, and changed how we are managing configs, I have altered the backend back to allow any values passed in as configs. You can get the list of config value names by opening the setup page in question (syp or ill) and then searching for "setting" - that will take you through each input element that has the class "setting", which they all do, and each one also has an ID, which is the config value name

**Comment by markmacgillivray** [comment]
Note though that changing those could be quite tricky, and I've written the code now to handle the current setting names and to assume that if there is not a true/string/list value then to get rid of it altogether, to keep the configs as short as possible. So everything defaults to not existing in the config at all unless there is a useful value for it. The only one that is really weird is "autorun", which when true means "don't autorun". It might be as well to just leave the config names as they are now.

**Comment by markmacgillivray** [comment]
For the open URL problem you mention above, that is the only one I am continuing to work on, I think all the rest have been fixed or I've given you a comment above. The open URL one will be to do with the new configs as you thought, and is probably just down to the fact that I have been working on that again over the last couple of days to get it to work with as short a config as possible, so you're probably seeing oddities with how I'm changing it. Should be finalised soon.

**Comment by JosephMcArthur** [comment]
> To get a list of all the config value names, the most up to date way is to always check the setup pages themselves. Given that we have changed quite a lot again, and changed how we are managing configs, I have altered the backend back to allow any values passed in as configs. You can get the list of config value names by opening the setup page in question (syp or ill) and then searching for "setting" - that will take you through each input element that has the class "setting", which they all do, and each one also has an ID, which is the config value name

> Note though that changing those could be quite tricky, and I've written the code now to handle the current setting names and to assume that if there is not a true/string/list value then to get rid of it altogether, to keep the configs as short as possible. So everything defaults to not existing in the config at all unless there is a useful value for it. The only one that is really weird is "autorun", which when true means "don't autorun". It might be as well to just leave the config names as they are now.

Let's talk about config names on Monday. 

> autorunparams would have been set on your account during testing, when I was working on the code. You can remove them by going to the setup page and using the config param to get rid of them, that is ?config.autorunparams=false. Then they will disappear from your config. They will only show up in user configs if the user does set some alternate values for them.

Just so I'm clear, you're saying their presence is not required, and just reflects at some point the code put them inadvertently while it was still being built.

The link should look like this: https://dev.openaccessbutton.org/syp2/setup?config.autorunparams=false right? I can't seem to get it to work, the config still shows the params.

> For the open URL problem you mention above, that is the only one I am continuing to work on, I think all the rest have been fixed or I've given you a comment above. The open URL one will be to do with the new configs as you thought, and is probably just down to the fact that I have been working on that again over the last couple of days to get it to work with as short a config as possible, so you're probably seeing oddities with how I'm changing it. Should be finalised soon.

Are you working on the above tick boxes:

> Ah, no, that's not right. It should be this response: http://www.lib.montana.edu/services/publication/scholarworks/?doi=10.15650/hebruniocollannu.89.2018.0221
> They should see this: https://shareyourpaper.org/10.15650/hebruniocollannu.89.2018.0221

> Why do you want the "Do another" link only to be a button on the congrats page? Why not the other pages that use it? The three other endings for SYP all have that button in the ending, on a separate line, and as I've defined it at the moment it would be a bit odd to alter the styling of it for just that one case, but I can do if you want. Just clarifying, in case you are not aware it comes out as a string on those places too.

Where do another is the primary action (i.e there is no other button on the page), e.g at the end of a workflow, then it can be a button.

TODO: Expand & check the above (have to run for a few)

> Do you want ALL non-button links bolded, or only those ones that are separate from surrounding text? e.g. should ones that appear inline in a sentence also be bolded?

TODO: Finish answering the above

**Comment by JosephMcArthur** [comment]
Righto:

- [ ] I'd say let's activate difftest now
- [ ] On the permission request workflow: https://shareyourpaper.org/10.15650/hebruniocollannu.89.2018.0221 the "I've got permission now!" button doesn't work as expected. After it opens the email something else should happen. Turns out this is also a problem on live. I don't have time right now to see what it was meant to do, but logging in case you can remember or otherwise for me to come back later.

**Comment by markmacgillivray** [comment]
I've done a bunch of the changes above, however some of them seem to have occurred because something has changed that means now none of the embed buttons are working. They definitely were before, so I'll have to investigate to find out what has caused them to stop. Until I find that out I can't finish testing the changes for the above. But as soon as I have fixed that, I will update about what I've fixed from above.

**Comment by JosephMcArthur** [comment]
Gotcha, fab, thanks!

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by markmacgillivray** [comment]
Also this means don't do any more testing yourself just now - can't tell what is working and what isn't. I'll let you know when it can be used again.

**Comment by markmacgillivray** [comment]
Weird button error fixed. Continuing to update the above list of issues. Vanity URLs has been done, ticked it again.

**Comment by markmacgillivray** [comment]
As far as I can see, passing the confirmed checksum and email in params is getting into the embed, and is being passed to the backend with the deposit, and is creating a deposit record as expected. Can you check this again, and we can discuss what you want it to do instead.

**Comment by markmacgillivray** [comment]
I couldn't find anything to indicate what the 'ive got permission now" button should do, apart from opening the email which it does do.

**Comment by markmacgillivray** [comment]
I don't see the same ROR issue we saw earlier - I see it still giving a response in relation to a ROR, but now it is the ROR being passed by the config you have set in your page, so it looks like the right answer. What I fixed was that it was picking up the wrong config and using the wrong ROR. If users can't set a ROR in the setup UI then a ROR won't get passed for them, so they won't get a ROR-based answer, BUT if you DO set a config which has a ROR in it, which it looks like you are doing, then you do get a ROR-based answer.

**Comment by markmacgillivray** [comment]
I think the only things left here now are talking about config names if you do want to change any, getting your config.autorunparams to change (did you try saving it on the setup page?), what you want the "ive got permissions" button to do, and setting up difftest on these new pages (or do you want the new pages moved to the old locations first, and tested from there?)

**Comment by markmacgillivray** [comment]
Just to be clear, this means testing is possible again now.

**Comment by JosephMcArthur** [comment]
Starting a comment for responses / testing. Expect updates:

> getting your config.autorunparams to change (did you try saving it on the setup page?), 

Just did it now and it worked!

> what you want the "ive got permissions" button to do

Can we have it act like a do another button + open the mailto. Somehow I can't find any evidence of what else I wanted it to do but that seems fine 🙃 

> and setting up difftest on these new pages (or do you want the new pages moved to the old locations first, and tested from there?

I'd say let's move these pages over to their old locations on dev (sans ill2/demo, which will be a new page)

**Comment by JosephMcArthur** [comment]
### Config rename plan

* note this *could* cause people who have embeds now, and update them *after* we release new config values, but don't use the new code, the have issues. 
* note this probably doesn't matter for syp (except our own instances & montana)

- [ ] get list of users of embeds as a csv for joe.
- [ ] get list of config values that are available
- [ ] continue to consider if pointing old embeds at new code will work
- [ ] consider managing problems like this in future

**Comment by markmacgillivray** [comment]
Fixing the weird behaviour of values disappearing in setup boxes on preview took forever. But it is sorted now. Also the green hover on syp setup pages is sorted. I've moved the pages back into /instantill and /shareyourpaper as well.

It is possible the fix that took forever may break the use of css/bootstrap in your own demo pages - it shouldn't but I haven't had time to check. If you see that it has, just let me know, and I will sort that, it shouldn't take too long. I'm not expecting it to be a problem, but it is related to the code I had to alter to get the fix to work, so mentioning it just in case.

So unfortunately there is not a whole lot of new stuff for you to test yet, sorry about that.

**Comment by markmacgillivray** [comment]
For getting the list of setting IDs from the page, the easiest way is to go the setup page and open dev tools and put this in it:

$('.setting').each(function() { console.log($(this).attr('id'))});

Then copy the list that comes out, and you can chuck the nonsense at the end and any undefined values, and you'll be left with all the IDs in the page.

**Comment by markmacgillivray** [comment]
For example here is the list from instantill/setup

ill_redirect_base_url
email
search
terms
ill_institution
problem_email
saypaper
book
other
illinfo
viewaccount
advancedform
cost
time
noillifoa
noillifsub
ill_redirect_params
sid
title
journal
doi
author
issn
volume
issue
page
published
pmid
year
notes
val
css
bootstrap
intropara
autorun
live
pilot
norequests

**Comment by markmacgillivray** [comment]
The SYP UI should not require a file if the user is doing a dark deposit, or if they are doing a deposit of something already OA for which we found the link, right?

**Comment by markmacgillivray** [comment]
The long "do another" button is fixed

**Comment by JosephMcArthur** [comment]
> The SYP UI should not require a file if the user is doing a dark deposit,
or if they are doing a deposit of something already OA for which we found
the link, right?

Correct. Just an email.

**Comment by markmacgillivray** [comment]
Where you say above "deposit-if-oa" is a good field name, I'd recommend using underscores instead of dashes if you want to separate words.

I think all issues here are done, I just need to get you a list of user embeds, and set up difftest.

Do you want the other pages under shareyourpaper/ and instantill/ to be switched to use the new code now, where relevant? So far I only switched the ones I directly worked on, that is, setup and demo. But for example you have other ones in there called test

**Comment by JosephMcArthur** [comment]
> Where you say above "deposit-if-oa" is a good field name, I'd recommend using underscores instead of dashes if you want to separate words.

Sure thing, underscores it is.

> I think all issues here are done, I just need to get you a list of user embeds, and set up difftest.

Ace. I should have some time to test and tidy up my jobs today.

> Do you want the other pages under shareyourpaper/ and instantill/ to be switched to use the new code now, where relevant? So far I only switched the ones I directly worked on, that is, setup and demo. But for example you have other ones in there called test

- [ ] Yes please. Test / index should be moved too. If you could handle that and let me know when it's done I'll test them.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Starting comment for the day! 

- [ ] change `https://zenodo.org/record/DEMO` to `https://zenodo.org/record/3703317#.XwBwmZP0m3I`. Just nicer to give a real record.

**Comment by markmacgillivray** [comment]
The setup/demo pages accepting/rejecting actual files seems to be quite different from what we had before, which looks like it has been coded specifically to return a particular example response in those cases. I'll need to look at that more to try to understand what you are asking for now, and how that can fit most easily with what we have without too much more time spent on it.

About min-width: I removed that from the buttons directly because you said you'd rather have it in the class. So if the user has bootstrap on (or bootstrap is on the page and nothing is set to not use it) then the bootstrap configs of that user will be used. That means we can't force the button widths and also allow their bootstrap to take full effect. I could add min-width declarations back directly into the buttons, but that does mean it may then override a preferred setting of the user, if they happen to have configured that to be something else in their own bootstrap, or in any of their own css that they wanted to provide. Are you OK with that?

About hitting back on the syp-montana URL, still to look at that.

About "we can help you make your paper open access, for free, wherever you publish" - it's not missing, but it appears that when not_a_library is not set, we intentionally replace that sentence with "share your paper with help from the library in REPO_NAME. Legally, for free, in minutes." What do you want it to do instead in those cases? not_a_library doesn't appear to have any other function, so if you don't want it to do that, there doesn't seem to be any reason for that config variable to exist.

**Comment by JosephMcArthur** [comment]
> About "we can help you make your paper open access, for free, wherever you publish" - it's not missing, but it appears that when not_a_library is not set, we intentionally replace that sentence with "share your paper with help from the library in REPO_NAME. Legally, for free, in minutes." What do you want it to do instead in those cases? not_a_library doesn't appear to have any other function, so if you don't want it to do that, there doesn't seem to be any reason for that config variable to exist.

But, not_a_library: true appears on the page, so it looks set to me. 

> The setup/demo pages accepting/rejecting actual files seems to be quite different from what we had before, which looks like it has been coded specifically to return a particular example response in those cases. I'll need to look at that more to try to understand what you are asking for now, and how that can fit most easily with what we have without too much more time spent on it.

It it worth a quick chat to make sure we're talking about the same thing, I know this is complex. I want the file checking system to work on these pages, but no deposits to happen (and the current fake responses where we'd otherwise do a deposit). 

> About min-width: I removed that from the buttons directly because you said you'd rather have it in the class. So if the user has bootstrap on (or bootstrap is on the page and nothing is set to not use it) then the bootstrap configs of that user will be used. That means we can't force the button widths and also allow their bootstrap to take full effect. I could add min-width declarations back directly into the buttons, but that does mean it may then override a preferred setting of the user, if they happen to have configured that to be something else in their own bootstrap, or in any of their own css that they wanted to provide. Are you OK with that?

Answer coming soon :)

**Comment by markmacgillivray** [comment]
Ah ha, I see what you mean, I had a "not" in front of "not_a_library", I'd thought it was another backwards name. Changed that,  works now.

**Comment by markmacgillivray** [comment]
Can't talk about setup/demo just now anyway, got other things on. Will msg you when I get back to it.

**Comment by markmacgillivray** [comment]
Here are the demo/setup cases in the backend code:

* find: if the find request is from instantill or shareyourpaper, and DOI passed in is 10.1234/567890 or the DOI starts with 10.1234/oab-syp- or title is the "Engineering a powerfully simple ILL..." one or the account that sent the request is either our live or demo account, then return a fixed response of metadata and ILL data.

* the above case would also call the permissions endpoint if the plugin is shareyourpaper, because permissions is called automatically for shareyourpaper requests. The permissions endpoint would also return a fixed response. If the DOI passed in was 10.1234/oab-syp-aam then the fixed response will be that archiving is allowed, and the version allowed is postprint.

* if a user proceeded to deposit a file from the syp demo page, it would send as one of our demo accounts. Or, anything that sent a DOI starting with 10.1234/oab-syp-, or sent a "demo" param, would receive a fixed demo response. It would contain nothing but demo: true, unless the DOI was 10.1234/oab-syp-aam, in which case it also returns the zenodo object part of the response, with the zenodo url set to https://zenodo.org/record/3703317

* if a user proceeded to deposit a file from the syp setup page, it would behave exactly as it behaves for them in any other setting.


Let me know what of the above you want changed.

**Comment by markmacgillivray** [comment]
Apart from that, I just need to know if you want the min-width setting added directly back to the buttons again. I don't think there is anything else outstanding. I need to get you the list of URLs, but that is separate to actual changes to the embed, and should be done shortly.

**Comment by markmacgillivray** [comment]
Also I'm looking at find response speed, but that is also separate to embed dev.

**Comment by JosephMcArthur** [comment]
- [ ] can we change the instantill preview default value to `10.1126/scitranslmed.3001922`

**Comment by JosephMcArthur** [comment]
> Apart from that, I just need to know if you want the min-width setting added directly back to the buttons again. I don't think there is anything else outstanding. I need to get you the list of URLs, but that is separate to actual changes to the embed, and should be done shortly.

I gave my thoughts in https://github.com/OAButton/discussion/issues/1513#issuecomment-654682478. It's the right option isn't clear let's talk. 

Thanks for https://github.com/OAButton/discussion/issues/1513#issuecomment-655961135! Let's talk about it on our permissions call tomorrow. Again, I'm not clear on if you're unclear on what I've already said.

**Comment by JosephMcArthur** [comment]
- [ ] hitting do another no longer resets the URL (e.g removing ?doi=10.1126/scitranslmed.3001922)

**Comment by markmacgillivray** [comment]
Remove triggering of demo responses by demo user account - only trigger by demo DOIs.

Add a check to see if a deposit came from our demo OR our setup page, and if so, deposit to zenodo sandbox even if on live.

**Comment by JosephMcArthur** [comment]
- [ ] setup difftest with the screens in all the embeds (the ones we made available at #... )

**Comment by markmacgillivray** [comment]
config rename done, but a question to resolve once Joe is back, about the "email" field. Also there is one in use in the embed called old_way which appears to have no way to set it in the setups. Not urgent, easy to solve, will discuss next week.

**Comment by markmacgillivray** [comment]
I tried testing using the shareyourpaper test page, but I still don't understand what counts as the correct response. It's not obvious from the descriptions what the page should look like. So we will need to look at that together.

Also I made a sheet for difftest to run on the panels of the embed, but I don't understand what it is you want to test on those panels. Passing the panel parameter was for being able to see the content of the panel so we could preview it in development. But how will it be useful to test that? Nothing could possibly change on those panels unless we change the content of the embed and deploy it, so a test will only ever alert us at exactly the time we know we are making a change anyway, it seems.

**Comment by markmacgillivray** [comment]
I explored find speed too, we can discuss that in meeting

**Comment by markmacgillivray** [comment]
replace email with owner and add code to the setup pages to set the owner value in the config to be the email address of the logged in user (the one configuring the embed)

**Comment by JosephMcArthur** [comment]
I've added `old_way` to the syp set up page. If you need to update anything to support that, let this serve as a heads up to do that!

**Comment by JosephMcArthur** [comment]
## Testing

- [ ] on https://dev.openaccessbutton.org/shareyourpaper/setup#menu when incognito I'm not asked to login, but I am on Instantill. See: https://recordit.co/UdX5CBUThf/gif

**Comment by JosephMcArthur** [comment]
Okay, testing done for the day!

**Comment by markmacgillivray** [comment]
For showing content when the embed hasn't been used yet - OK, what should I do about that? There is an "embeddedexample" box followed by one for when there is no example, are those what you mean? Or do you need something else there?

Save & Continue on syp/setup#outreach has nowhere to go after it, there appears to be no final div for that page. So, it fails. Whereas on instantill you do have followup section. So, you need to decide what you want it to show last.

Hitting try it on the demo works for me. Can you check again, or let me know of the errors you get, if any?

About submitting and getting an extremely long and broken open URL, what is broken about it? When I click complete request it opens an IUPUI interlibrary loan page, with a bunch of URL params in it. Is that not what you expect it to do?

Can talk about citation searches at next meeting, yes. First points on that though, I'd guess, would be that I thought you said instantill should not do citations, and the text above the box says to enter a title, doi, or URL. It doesn't say it can do citations. So it was assuming anything not a doi or a url was a title, and then also assuming that it must be the correct title, because you also want instantill to favour user input over what we find ourselves. I've changed this a bit so that now it does do the guessing to try to work out that the entered value is a citation - this is not always successful, but it never was. This is also probably a useful example to discuss about the problem of testing and the requirements the thing should meet before release, and whether or not such changes/problems should delay a release.

For the remaining unticked issues that I have not specifically mentioned, I don't get the same problems. Can you clear your config and check? You can use the URL param local=false to not use a local config, and you can also use clear=true to delete a local config.

**Comment by JosephMcArthur** [comment]
> For showing content when the embed hasn't been used yet - OK, what should I do about that? There is an "embeddedexample" box followed by one for when there is no example, are those what you mean? Or do you need something else there?

- [ ] Yes, maybe it is already there and I missed it. Will circle back.

> Save & Continue on syp/setup#outreach has nowhere to go after it, there appears to be no final div for that page. So, it fails. Whereas on instantill you do have followup section. So, you need to decide what you want it to show last.

After the final section it should just go back to menu like with InstantILL.
 
> Hitting try it on the demo works for me. Can you check again, or let me know of the errors you get, if any?

Works for me too

> About submitting and getting an extremely long and broken open URL, what is broken about it? When I click complete request it opens an IUPUI interlibrary loan page, with a bunch of URL params in it. Is that not what you expect it to do?

Did you change something? It seems to work now. 

> Can talk about citation searches at next meeting, yes. First points on that though, I'd guess, would be that I thought you said instantill should not do citations, and the text above the box says to enter a title, doi, or URL. It doesn't say it can do citations. So it was assuming anything not a doi or a url was a title, and then also assuming that it must be the correct title, because you also want instantill to favour user input over what we find ourselves. I've changed this a bit so that now it does do the guessing to try to work out that the entered value is a citation - this is not always successful, but it never was. This is also probably a useful example to discuss about the problem of testing and the requirements the thing should meet before release, and whether or not such changes/problems should delay a release.

Yes let's include this in discussion. However, for the avoidance of doubt now, InstantILL should be able to make use of what we just developed to do good citation searches. If we get back good information from crossref, or pull it out ourself, the 'title' at the top of the results page should use either the title given by crossref or what we think the title is. 

> For the remaining unticked issues that I have not specifically mentioned, I don't get the same problems. Can you clear your config and check? You can use the URL param local=false to not use a local config, and you can also use clear=true to delete a local config.

Sure thing! Will get back to you.

**Comment by JosephMcArthur** [comment]
It seems that `noembeddedexampleavailable` is not showing. The expected copy is in set up page content, but it seems like some of the function that was on that page is now in the embed ui code. Maybe this should be moved too into the ui code, or maybe the ui code is failing to talk to the set up page code. I don't know, but the various bits are there and I confirm they're not showing up.

**Comment by JosephMcArthur** [comment]
Right, above I talk about the SYP demo not working when `try it` is pressed. I couldn't replicate that later in the day, or now, and presumed you fixed it. But, now the InstantILL does seemingly the same error (can't promise you the console error is the same, but it looks similar). 

See: http://g.recordit.co/TKp71MwJEO.gif

It seems like a very frequent regression for one or both of these to be not working. Anything we can do it make it more robust?

**Comment by JosephMcArthur** [comment]
> For the remaining unticked issues that I have not specifically mentioned, I don't get the same problems. Can you clear your config and check? You can use the URL param local=false to not use a local config, and you can also use clear=true to delete a local config.

I've tried this, and it's still not working as I'd expect. There's a few things going on, and I think a call might help unpick (especially if you can't replicate).

A couple of things to discuss:

* I'm seeing `email` in the config. I think `email` should be owner, but I'm also seeing owner. Why is that?
* I'm seeing `adminemail` in the config. I don't know at all what that its, it's not in our config list at all.
* I'm seeing SYP config values turning up in InstantILL.
* It still seems `owner` is taking a value from my cache or something.

Here's what I'm seeing: https://www.dropbox.com/s/edzgpaoewf83z1r/Screenshot%202020-07-23%2009.05.44.png?dl=0. I'm logged in as joseph.mcarthur.10+default@gmail.com.

**Comment by JosephMcArthur** [comment]
Another SYP demo issue (separate to the above, it's later on). 

I don't see the content expected with: https://dev.shareyourpaper.org/demo#wrong. The RHS should show the content starting `Authors have a safety net`.

- [ ] Fix

**Comment by JosephMcArthur** [comment]
>> Save & Continue on syp/setup#outreach has nowhere to go after it, there appears to be no final div for that page. So, it fails. Whereas on instantill you do have followup section. So, you need to decide what you want it to show last.

> After the final section it should just go back to menu like with InstantILL.

Right, the same thing is now happening with InstantILL after I hide a section from the flow that needed to be hidden. 

I don't know how to set up the final section in the flow to go back to the menu. So, will just ask that on instantill save & continue on https://dev.openaccessbutton.org/instantill/setup#analytics takes you back to the menu. On syp, https://dev.openaccessbutton.org/shareyourpaper/setup#outreach should.

**Comment by JosephMcArthur** [comment]
> > For the remaining unticked issues that I have not specifically mentioned, I don't get the same problems. Can you clear your config and check? You can use the URL param local=false to not use a local config, and you can also use clear=true to delete a local config.
> 
> I've tried this, and it's still not working as I'd expect. There's a few things going on, and I think a call might help unpick (especially if you can't replicate).
> 
> A couple of things to discuss:
> 
> * I'm seeing `email` in the config. I think `email` should be owner, but I'm also seeing owner. Why is that?
> * I'm seeing `adminemail` in the config. I don't know at all what that its, it's not in our config list at all.

remote config (with old values) are being pulled in. 

> * I'm seeing SYP config values turning up in InstantILL.

likely the same. we think.

> * It still seems `owner` is taking a value from my cache or something.

yes, the local storage will pull any values you have and use them.

> Here's what I'm seeing: https://www.dropbox.com/s/edzgpaoewf83z1r/Screenshot%202020-07-23%2009.05.44.png?dl=0. I'm logged in as [joseph.mcarthur.10+default@gmail.com](mailto:joseph.mcarthur.10+default@gmail.com).

Planning to turn off local storage, so login will be required to set up embeds properly (but you can browse the set up page without it)

- [ ] Joe: make sure the login is understood as basically essential
- [ ] Mark: turn off local storage

**Comment by JosephMcArthur** [comment]
- [ ] Login as: qZooaHWRz9NLFNcgR & eZwJ83xp3oZDaec86 and config as demo values. dev + live: mark+instantill@cottagelabs.com

**Comment by JosephMcArthur** [comment]
- [ ] on https://dev.shareyourpaper.org `Try an example 10.1126/scitranslmed.3001922 or learn more.` doesn't appear after hitting back. It should. To replicate: http://recordit.co/ZkQC3G8gPC.gif

**Comment by JosephMcArthur** [comment]
> > https://dev.instantill.org/demo#part3 shows email submission: https://www.dropbox.com/s/z6ewo8s7ktsum6a/Screenshot%202020-07-22%2009.16.45.png?dl=0. It should show link submission: https://www.dropbox.com/s/yewyb5upat6o6hd/instantill%20link.png?dl=0. This is flagged as an issue above but I'm trying to make clearer here. We've discussed this before and you've said it's just a quick config change.
> 
> * [x]  Login as: qZooaHWRz9NLFNcgR & eZwJ83xp3oZDaec86 and config as demo values. dev + live: [mark+instantill@cottagelabs.com](mailto:mark+instantill@cottagelabs.com)

I've updated this, see: https://github.com/OAButton/website/commit/f94c664edfb66a6ba74111ceea285a61f3c71bd2. It may be incorrect. Regardless, it hasn't done what I'd expect.

While testing, I also noticed that:

- [ ] the demo seems to not use `val` when given, for example `val="Factors associated with mental distress among undergraduate students in northern Tanzania"` just gives the static `Engineering a Powerfully Simple Interlibrary Loan...` response.

**Comment by JosephMcArthur** [comment]
- [ ] I don't see the ghostinspector tests being run on commit yet, which I thought I set up. Can you see if you can get them going: https://ghostinspector.com/docs/integration/github/

**Comment by JosephMcArthur** [comment]
> > > For the remaining unticked issues that I have not specifically mentioned, I don't get the same problems. Can you clear your config and check? You can use the URL param local=false to not use a local config, and you can also use clear=true to delete a local config.
> > 
> > 
> > I've tried this, and it's still not working as I'd expect. There's a few things going on, and I think a call might help unpick (especially if you can't replicate).
> > A couple of things to discuss:
> > 
> > * I'm seeing `email` in the config. I think `email` should be owner, but I'm also seeing owner. Why is that?
> > * I'm seeing `adminemail` in the config. I don't know at all what that its, it's not in our config list at all.
> 
> remote config (with old values) are being pulled in.
> 
> > * I'm seeing SYP config values turning up in InstantILL.
> 
> likely the same. we think.
> 
> > * It still seems `owner` is taking a value from my cache or something.
> 
> yes, the local storage will pull any values you have and use them.
> 
> > Here's what I'm seeing: https://www.dropbox.com/s/edzgpaoewf83z1r/Screenshot%202020-07-23%2009.05.44.png?dl=0. I'm logged in as [joseph.mcarthur.10+default@gmail.com](mailto:joseph.mcarthur.10+default@gmail.com).
> 
> Planning to turn off local storage, so login will be required to set up embeds properly (but you can browse the set up page without it)
> 
> * [x]  Joe: make sure the login is understood as basically essential
> * [x]  Mark: turn off local storage

I had to clear everything to restore what I expected, but it seems now too. \o/

**Comment by markmacgillivray** [comment]
ghost inspector tests seem to be working to me... what is it you are wanting to see that does not appear to be happening?

**Comment by markmacgillivray** [comment]
Note that to get tests to pass/fail on actual pushed code, you should base them on URLs on the dev.openaccessbutton.org. The shareyourpaper/instantill ones are all cached by cloudflare. Or we can change the cache settings so that the dev versions of syp/ill are not cached.

**Comment by JosephMcArthur** [comment]
Oh, I see the tests now! And, they just failed on your last push ;) Did you get a notification?

- [ ] don't cache dev versions of syp/iill at cloudflare

**Comment by JosephMcArthur** [comment]
Ah, you won't have gotten an email, but I just set it up so that you should. But I also didn't, but should, so I'll see why...

**Comment by markmacgillivray** [comment]
I got an email that time, having just run them again to test the cloudflare changes

**Comment by markmacgillivray** [comment]
I made some changes to how the embed and API handles demo stuff today - took it all out of the API and tried putting it all in the embeds instead. Hopefully that will stop the repetition where we try different responses on different pages for different values etc, and end up changing that code a lot. I have still to test it, then do some more API stuff tomorrow to also get the permissions things to a point that's good for discussion, so we can cover both these when we talk on thursday.

**Comment by JosephMcArthur** [comment]
Kay, I presume you saw the test fail? That's a real test :) Looks like the demo doesn't accept the demo doi.

**Comment by JosephMcArthur** [comment]
- [ ] our oab homepage test doi `10.1126/science.196.4287.293` isn't giving the right response on dev.

**Comment by markmacgillivray** [comment]
Hmm yes that is weird, and not related to refactor of embeds as far as I can tell. I've done some checking, but will take a bit longer so I have made an issue to track it

https://github.com/OAButton/discussion/issues/1636

**Comment by JosephMcArthur** [comment]
This is going to be a tricky one to describe maybe...

- [ ] For the sections here: https://dev.openaccessbutton.org/shareyourpaper/setup#preferences-general, the save button uses the value I'd expect the next div's save button to use. Said another way, https://dev.openaccessbutton.org/shareyourpaper/setup#preferences-oa is given the preview from the previous save and continue button I'd expect on https://dev.openaccessbutton.org/shareyourpaper/setup#preferences-pdfs. The net result of this is that the preview is wrong at first. This can be corrected by hitting `Preview`.

**Comment by JosephMcArthur** [comment]
As I make tests, I'm conscious of not wanting to double up on test where that's not helpful. 

For instance, take this test https://app.ghostinspector.com/tests/5f23cf985e12c014aeae5b2b. I'm looking at testing that updates to the config get reflected in the preview and code (arguably I should have have those two separate tests...). I've done this on SYP, but I of course care that InstantILL's set up page does the same thing. My hope is though that it's not required, so it's all in libraries now, and so if InstantILL's set up page breaks in this way then SYPs should also be broken. To what extent do you think that's a safe assumption for things that we have libraries for?

**Comment by markmacgillivray** [comment]
The covid query thing on email has no issue relating to it, so documenting here, since everything else is going on here at the moment :)

I ran the query to get the values out, but didn't have permissions info, so wrote a script to get those for each record. Haven't added scraping for emails yet as that would make the script take a fair bit longer. However, can rerun with that later. Once the current scripts finishes I'll respond to the email with a link.

The interesting thing I noticed is that Ricks permissions often responded with failures, and when I checked some manually, it appeared to be because they didn't register them as valid DOIs. Here is an example one:

10.3760/cma.j.issn.0578-1310.2020.03.002

It does dereference, so it does seem to be valid, although it does point to what looks like a chinese publication. Does Ricks not cover all DOIs? Probably doesn't matter, given that we are rewriting that anyway, but something to keep in mind for our own work.

Issues opened above are being worked on, will update this issue again once they are closed (and the other issue about the main example DOI on the front page).

**Comment by markmacgillivray** [comment]
Also figshare DOIs failing?

**Comment by JosephMcArthur** [comment]
Currently the syp demo is having some trouble. The test is passing as i set it up wrong, oh dear!

See the syp demo main flow is failing. Note the missing URL and also the RHS is not showing the `id=success` as it should. 

![image](https://user-images.githubusercontent.com/4953703/89734868-aba54880-da56-11ea-8f5b-4b8fbecc4c25.png)

And also I can't see the demo providing the ability to test the whole deposit process without putting things in the real zenodo as discussed on the past few calls and above.

**Comment by JosephMcArthur** [comment]
> As I make tests, I'm conscious of not wanting to double up on test where that's not helpful.
> 
> For instance, take this test https://app.ghostinspector.com/tests/5f23cf985e12c014aeae5b2b. I'm looking at testing that updates to the config get reflected in the preview and code (arguably I should have have those two separate tests...). I've done this on SYP, but I of course care that InstantILL's set up page does the same thing. My hope is though that it's not required, so it's all in libraries now, and so if InstantILL's set up page breaks in this way then SYPs should also be broken. To what extent do you think that's a safe assumption for things that we have libraries for?

Yes, I should!

**Comment by JosephMcArthur** [comment]
- [ ] remove oab_ from live embed codes. Leave on dev ones.

**Comment by markmacgillivray** [comment]
@JosephMcArthur demos step through as expected again. You may want to check the values the different parts show again, and let me know if they are what you want, but the functionality at least is there.

**Comment by JosephMcArthur** [comment]
It's looking good I think. The only thing i can find ary is that on the setup page the wrong paper gives me this response rather than the normal wrong paper response (demo gives the correct one):

![image](https://user-images.githubusercontent.com/4953703/89844724-58c1b300-db74-11ea-8c30-3fbde22ee786.png)

**Comment by markmacgillivray** [comment]
I did some more work on this and tested on a few more pages, it seems to me like it is working. I didn't actually see the error you show there - that could have been caused by the backend not responding at the time. I've checked that too, and it does respond when I try it. However I also did see that we don't succeed in getting any text out of the PDF file you use there - if you're not expecting that one to succeed anyway, then perhaps that is OK.

Let me know whenever you're happy for me to push things out to live, and I'll start doing that. Until then I'm continuing with permissions API stuff.

**Comment by JosephMcArthur** [comment]
- [ ] add id's to embeds, demo, and setup pages to assist with automated testing being more robust

**Comment by markmacgillivray** [comment]
All divs, links/buttons, and inputs on the embed now have IDs. Where possible the ID has same or similar name as the most important (or only) class for the div, but sometimes they cannot match as mentioned, because there are divs that show for different states, and some divs that show for more than one state.

I think for the embed this should give sufficient granularity for the tests, as any relevant content should show in relation to a particular div ID, so you can test for visibility of that ID. Let me know if there is anywhere you need more precision, and where the class or other methods of identification are too brittle.

The demo and setup pages also now have IDs for every div that has a particular section of content. I haven't added IDs to every input, button, etc on the setup pages, I think the section detail may be enough here, but let me know if not.

**Comment by JosephMcArthur** [comment]
Righto, we're not *quite* done yet (e.g I need to check the demo a bit more, plus refine testing a bit) but I think we should work to push this live now.

**Comment by JosephMcArthur** [comment]
Sorry for the thousands of test emails today... been upgrading them as we discussed. 20% through or what not (plus making new ones). I'm going to pause until you and I can review to make sure I'm getting it right now (but still trust the test and screenshots for now!)

Two things though, these two tests are actually failing:
* https://app.ghostinspector.com/tests/5f36ab00fb816a0cd2dd45b7
* https://app.ghostinspector.com/tests/5f36abaafb816a0cd2dd50dd

- [ ] They should have the same response as the demo (ie these should response as if they're doing a normal deposit, except put it in the sandbox even on live so that people can test), and if that happens the tests should pass.

This is as discussed [here](https://github.com/OAButton/discussion/issues/1513#issuecomment-671660216) and [here](https://github.com/OAButton/discussion/issues/1513#issuecomment-671760399).

Of note, I get a javascript error on both:

`Access to XMLHttpRequest at 'https://dev.api.cottagelabs.com/service/oab/deposit?_=1597418441901' from origin 'https://dev.openaccessbutton.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by markmacgillivray** [comment]
OK we seem to be going in a bit of a circle on this again. I've looked at the failing tests and tried to replicate, but can't. I've also looked through these comments on this issue, and many others, to try to understand again what the end result is supposed to be.

For the first test: https://app.ghostinspector.com/tests/5f36ab00fb816a0cd2dd45b7

* when I try it, it works as I would expect. I put in the DOI, it comes back asking for an email address and a file, I put in the "Wrong article for test paper" file which appears to be the same one you are using, and it comes back with "Hmm, something looks wrong" and the "try uploading again" option. There is no error on the dev tools. This is what I would expect the result to be, and in comments above this appears to match what I have said it should now do, and which you have agreed to, as far as I can tell. Also, if I put the same DOI into the demo page and then the same email and file, I get exactly the same response, so I don't understand what you are asking me to fix when you say this should have the same response as the demo, sorry - it appears to me that they do. The two comments that you linked to don't seem to make it any clearer.

For the second test: https://app.ghostinspector.com/tests/5f36abaafb816a0cd2dd50dd

* Again, this seems to work as expected for me, I get no error. I put in the DOI, then provide an email address and the correct file. It accepts it, and the backend responds successfully having put it into zenodo (in the sandbox because this is on dev) and the UI shows the success page with the correct zenodo section visible, showing the zenodo sandbox URL of the file that has been uploaded. I've checked the comments above, and this does seem to be how I'd expect it to work, and seems to me to match what has been discussed above. I've tried this one on the demo page too, and it behaves the same way, which is also what I'd expect given previous comments, so I'm stuck here too, not sure what it is you want me to change it to.

Sorry this has taken so long to check through, and hasn't yet resulted in any progress. Please let me know what you want them to do instead.

**Comment by JosephMcArthur** [comment]
Discussed and sorted over chat 🥇 . Mark was logged in, I wasn't, and the config for what to do in each state was different than on demo. That's changed, and the tests pass now!

**Comment by JosephMcArthur** [comment]
All the tests are now updated to use the new assumptions and IDs, hurray 💯 . Will keep an eye on them, but I think we can tick that off the list.

**Comment by JosephMcArthur** [comment]
Mark is it possible to have @openaccessbutton.org and @email.ghostinspector.com addresses ignored by email validation? Would be helpful for testing.
